### ISSUE TITLE
Add TIL: Outlook Shift + Del Nuclear delete option

### ISSUE THREAD

**Issue by chadmando** [chadmando/til#20]
In MS Outlook (Desktop?) using Shift + Del nukes your message(s).  No archive, no deleted folder. The only recovery option becomes eDiscovery.

**Comment by RhetTbull** [comment]
I occasionally declare "email bankruptcy" when inbox gets to crazy. Ctrl + A (select all), Shift-Delete (nuke all)

**Comment by chadmando** [comment]
@RhetTbull

> I occasionally declare "email bankruptcy" when inbox gets to crazy. Ctrl + A (select all), Shift-Delete (nuke all)

 I can only imagine how liberating that must feel (for a few minutes at least).
